### PR TITLE
Support turnip version 4 and limit counts to features

### PR DESCRIPTION
**Pull request by marcoadkins**

### CODE REVIEW

**Comment by marcoadkins** [comment]
@gongo Mind getting this merged in?

**Comment by gongo** [comment]
@marcoadkins Sorry for the late reply. 

`bundle exec rake test` fails now, so please fix it. (Travis CI is not running now)

**Comment by marcoadkins** [comment]
@gongo Updated. Rake test is passing now:
```
Finished in 0.065119 seconds.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
51 tests, 70 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
783.18 tests/s, 1074.96 assertions/s
```

**Comment by gongo** [comment]
@marcoadkins Thank you for good pull request!

**Comment by gongo** [comment]
This changes has been released in [v0.8.0](https://github.com/gongo/turnip_formatter/releases/tag/v0.8.0)

**Pull request merged**
