### PR TITLE
update dependency to be able to use turnip 2.x

### PR DESCRIPTION
**Pull request by KazuCocoa**
How about to allow using turnip 2.0 ?

### CODE REVIEW

**Comment by gongo** [comment]
Hi @KazuCocoa 

Sorry, I forgot to update and release ([0.4.0-dev](https://github.com/gongo/turnip_formatter/tree/0.4.0-dev) branch).
I will lock `turnip` version to `~>2.0.0` soon.

**Comment by KazuCocoa** [comment]
:+1: 
thanks !
Close this PR

**Comment by gongo** [comment]
@KazuCocoa 

I've released `turnip_formatter 0.4.0` that use `turnip 2.x` :muscle:

**Comment by KazuCocoa** [comment]
Thanks ! :cool: :grinning:

**Pull request closed without merging**
