### PR TITLE
Add puts 

### PR DESCRIPTION
**Pull request by JohnBat26**

### CODE REVIEW

**Comment by gongo** [comment]
Yeah :smile: 
Thanks for pull-request :+1: 
But I cannot understand necessity of this patch for me right now :muscle: 
See you next time :wave:

**Comment by JohnBat26** [comment]
@gongo  Add "puts FAILED" for Jenkins, else it doesn't recognize FAILED steps

**Comment by gongo** [comment]
You should be able to recognize the failed steps using a status code of RSpec

**Comment by JohnBat26** [comment]
@gongo hmm. If I start test as:

~~~
 bundle exec rspec  -r turnip/rspec spec/acceptance/ -r turnip_formatter --format RSpecTurnipFormatter --out report.html
~~~

then I don't get  any info info in console. And Jenkins does false positive decision about build.

I one of my steps failed, Jenkins didn't know about it at all :(

~~~

~~~

**Comment by gongo** [comment]
Try add to the end:

```diff
- bundle exec rspec  -r turnip/rspec spec/acceptance/ -r turnip_formatter --format RSpecTurnipFormatter --out report.html
+ bundle exec rspec  -r turnip/rspec spec/acceptance/ -r turnip_formatter --format RSpecTurnipFormatter --out report.html --format documentation
```

**Comment by JohnBat26** [comment]
Ok. Thanks :+1:

**Pull request closed without merging**
